"""IMMUTABLE evaluator for the autoresearch loop.

DO NOT EDIT THIS FILE as part of the inner loop. Editing it constitutes
"changing the rules of the game" and invalidates results across iterations.

Layout:
- Walk-forward over [BACKTEST_START, TEST_BOUNDARY): rolling 2y train,
  6mo validation, slide 3mo. Each validation fold contributes one Sortino;
  the agent optimizes the mean across folds.
- [TEST_BOUNDARY, BACKTEST_END]: SEALED test set. Only revealed in
  mode="promotion".

Run as a script:
    uv run python prepare.py research      # validation only
    uv run python prepare.py promotion     # also reveals test-set scores
"""
from __future__ import annotations

import importlib
import inspect
from datetime import date, datetime, timedelta
from types import ModuleType

import backtrader as bt
import numpy as np
import pandas as pd

from backtest.engine import run_backtest
from backtest.metrics import (
    calmar,
    hit_rate,
    max_drawdown,
    profit_factor,
    sortino,
    turnover,
)  # max_drawdown also used directly to compute the chained-fold aggregate DD
from backtest.risk import validate as validate_risk
from data.ingest_prices import read_prices
from data.universe import get_universe_at, snapshot_dates

BACKTEST_START = date(2020, 1, 1)
# India rebuild: NSE bhav archive starts cleanly in late 2019; 2020-01-01 is
# the first month with dense data across the Nifty 500. Train+val spans
# 2020-01 → 2024-12 (~5y, walk-forward folds with 2y train / 6m val / 3m slide);
# sealed test = 2025-01 → 2026-05-14 (~16 months, covers the Jan-26 → Mar-26
# drawdown which is an adversarial regime for momentum strategies — passing
# sealed test here is a meaningful signal). Per spec §6.1.
BACKTEST_END = date(2026, 5, 14)
TEST_BOUNDARY = date(2025, 1, 1)
TRAIN_DAYS = 504
VAL_DAYS = 126
SLIDE_DAYS = 63

# Indicator burn-in (audit 2026-05-15 Fix 1). 12-1 momentum needs ~274
# trading days of prior history before it produces ANY signal; a 126-calendar
# (~85-trading-day) val window alone leaves it permanently None → the
# strategy never trades and every metric scores an inert book. We therefore
# load WARMUP_CALENDAR_DAYS of history BEFORE each scored window so the
# strategy enters it already warmed and invested (as it always is live), then
# score ONLY the in-window slice (see _score_window `score_start`). 520
# calendar days ≈ 370 trading days, comfortably > 274 with holiday margin.
# Excluded from scoring, so over-provisioning costs only load time, never
# correctness.
WARMUP_CALENDAR_DAYS = 520
INITIAL_CASH = 50_000.0

# Personal-take-home estimate. Indian resident on Indian (domestic) equities:
# flat 15% STCG (holding < 12 months) and 10% LTCG on gains above a ₹1L
# annual exemption (holding >= 12 months). Reported as a side-panel signal
# only — doesn't enter the agent's optimization (a flat haircut is
# Sortino-invariant). Surcharges (10–37% above ₹50L total income) are NOT
# modeled here; adjust manually if your bracket differs.
STCG_RATE = 0.15
LTCG_HOLDING_DAYS = 365   # 12 calendar months
LTCG_THRESHOLD_INR = 100_000   # ₹1L annual LTCG exemption per FY


# Skip feeds that don't have enough bars for the strategy's longest indicator
# warmup (50-day SMA + small safety margin). With multi-feed strategies,
# loading short-history tickers crashes backtrader's vectorized indicator
# pass with an IndexError. Single-feed didn't expose this because Cerebro
# only built indicators on the first feed.
_MIN_BARS_PER_FEED = 60


def _load_feeds(
    start: date, end: date, tickers: list[str]
) -> dict[str, pd.DataFrame]:
    """Load OHLCV from local DuckDB. Tickers with fewer than _MIN_BARS_PER_FEED
    rows in [start, end] are silently skipped (recent IPOs, mid-window adds,
    delistings).

    Raises only if NO tickers survive, which indicates a setup problem.
    """
    feeds: dict[str, pd.DataFrame] = {}
    for tkr in tickers:
        df = read_prices(tkr, start.isoformat(), end.isoformat())
        if len(df) < _MIN_BARS_PER_FEED:
            continue
        df = df.set_index(pd.DatetimeIndex(df["date"])).drop(columns=["date"])
        feeds[tkr] = df
    if not feeds:
        raise RuntimeError(
            f"No price data with >= {_MIN_BARS_PER_FEED} bars in [{start}, {end}]. "
            "Run data.ingest_prices first."
        )
    return feeds


def _pit_universe(window_end: date) -> tuple[list[str], dict]:
    """Point-in-time universe for a window ending `window_end`.

    Returns (sorted member union, {snapshot_date: frozenset(tickers)}) using
    ONLY snapshots dated on/before `window_end` — never a future snapshot.
    The strategy resolves the most-recent snapshot ≤ each rebalance date from
    this map. This is audit-2026-05-15 Fix B: it replaces the single frozen
    get_universe_at(BACKTEST_START) that made the whole walk-forward run on
    today's universe. Empty union ⇒ the window predates any snapshot (the
    pre-2021-11 data-starved period); the caller skips such folds.
    """
    sd = [d for d in snapshot_dates() if d <= window_end]
    ubd = {d: frozenset(get_universe_at(d)) for d in sd}
    union = sorted(set().union(*ubd.values())) if ubd else []
    return union, ubd


def _find_strategy_class(module: ModuleType) -> type:
    """Return the single bt.Strategy subclass defined in `module`."""
    candidates = [
        cls for _, cls in inspect.getmembers(module, inspect.isclass)
        if issubclass(cls, bt.Strategy) and cls is not bt.Strategy
    ]
    if not candidates:
        raise RuntimeError(
            f"No bt.Strategy subclass found in {module.__name__}"
        )
    if len(candidates) > 1:
        names = [c.__name__ for c in candidates]
        raise RuntimeError(
            f"Multiple bt.Strategy subclasses in {module.__name__}: {names}. "
            "Define exactly one."
        )
    return candidates[0]


def _as_date(x) -> date:
    """Normalize a date / datetime / Timestamp / ISO-string to date."""
    if isinstance(x, date) and not isinstance(x, datetime):
        return x
    if isinstance(x, datetime):
        return x.date()
    ts = pd.Timestamp(x)
    return ts.date()


def _score_window(
    strategy_cls: type,
    feeds: dict[str, pd.DataFrame],
    universe_by_date: dict | None = None,
    score_start: date | None = None,
) -> dict:
    """Run strategy on a single time window; return per-window scoring dict.

    `universe_by_date` ({snapshot_date: frozenset(tickers)}) is forwarded to
    the strategy so it restricts entries to the point-in-time universe at
    each rebalance (audit-2026-05-15 Fix B).

    `score_start` (audit-2026-05-15 Fix 1): when set, the feeds include an
    indicator-burn-in runway BEFORE this date. The strategy trades through
    the warm-up (entering `score_start` already invested, as it always is
    live), but ALL metrics are computed ONLY from `score_start` onward —
    warm-up bars/trades are excluded so they cannot leak into Sortino,
    drawdown, returns, turnover, or the chained equity curve downstream.
    Metric *definitions* are unchanged; only the window they see is the
    intended val/test window. score_start=None ⇒ legacy behaviour (whole
    fed window scored), preserving signal_today / existing tests.
    """
    result = run_backtest(
        strategy_cls, feeds, initial_cash=INITIAL_CASH,
        strategy_kwargs={"universe_by_date": universe_by_date}
        if universe_by_date else None,
    )
    daily = result["daily_returns"]
    trades = result["trades"]
    gross = result["gross_exposure_daily"]
    trade_count = result["trade_count"]

    if score_start is not None:
        # Slice raw daily returns to the scored window, then REBUILD the
        # equity curve from the slice so every downstream consumer
        # (Sortino, max_dd, chained equity, pre_tax_return_mean, risk,
        # gross exposure) sees only in-window P&L. The cut happens here —
        # before _score_window returns — because evaluate() reuses these
        # objects in many places (Codex review 2026-05-15).
        if len(daily) > 0:
            d_mask = [_as_date(i) >= score_start for i in daily.index]
            daily = daily[pd.Series(d_mask, index=daily.index)]
        eq = (1 + daily).cumprod() * INITIAL_CASH if len(daily) > 0 \
            else pd.Series(dtype=float)
        if len(gross) > 0:
            g_mask = [_as_date(i) >= score_start for i in gross.index]
            gross = gross[pd.Series(g_mask, index=gross.index)]
        if len(trades) > 0 and "exit_date" in trades.columns:
            keep = trades["exit_date"].map(
                lambda v: v is not None
                and not pd.isna(v)
                and _as_date(v) >= score_start
            )
            trades = trades[keep].reset_index(drop=True)
        # Closed round-trips realised in-window (TradeRecorder keys by
        # exit_date) — the consistent count for hit_rate/profit_factor.
        trade_count = int(len(trades))
    else:
        eq = result["equity_curve"]

    avg_eq = float(eq.mean()) if len(eq) > 0 else INITIAL_CASH

    return {
        "sortino": sortino(daily),
        "calmar": calmar(daily, eq) if len(eq) > 0 else 0.0,
        "max_dd": max_drawdown(eq),
        "hit_rate": hit_rate(trades),
        "profit_factor": profit_factor(trades),
        "turnover": turnover(trades, avg_eq),
        "trade_count": trade_count,
        "equity_curve": eq,
        "trades": trades,
        "gross_exposure_daily": gross,
    }


def _walk_forward_folds(
    start: date, end: date
) -> list[tuple[date, date, date, date]]:
    """Yield (train_start, train_end, val_start, val_end) tuples."""
    folds: list[tuple[date, date, date, date]] = []
    val_start = start + timedelta(days=TRAIN_DAYS)
    while val_start + timedelta(days=VAL_DAYS) <= end:
        train_start = val_start - timedelta(days=TRAIN_DAYS)
        train_end = val_start - timedelta(days=1)
        val_end = val_start + timedelta(days=VAL_DAYS) - timedelta(days=1)
        folds.append((train_start, train_end, val_start, val_end))
        val_start += timedelta(days=SLIDE_DAYS)
    return folds


def evaluate(strategy_module: ModuleType, mode: str = "research") -> dict:
    """Score a strategy module.

    mode='research'   → returns mean validation Sortino + side panel + risk.
                        Test-set scores are NOT included; the agent never sees them.
    mode='promotion'  → also reveals the locked test-set scores. Run by the
                        human at promotion gate, never by the agent.
    """
    if mode not in ("research", "promotion"):
        raise ValueError(f"mode must be 'research' or 'promotion', got {mode!r}")

    strategy_cls = _find_strategy_class(strategy_module)

    fold_scores: list[dict] = []
    skipped_folds = 0
    for (_train_s, _train_e, val_s, val_e) in _walk_forward_folds(
        BACKTEST_START, TEST_BOUNDARY
    ):
        members, fold_ubd = _pit_universe(val_e)
        if not members:
            # Window predates any universe snapshot (data-starved early
            # period). Skip rather than fabricate membership.
            skipped_folds += 1
            continue
        feeds = _load_feeds(
            val_s - timedelta(days=WARMUP_CALENDAR_DAYS), val_e, members
        )
        fold_scores.append(
            _score_window(strategy_cls, feeds, fold_ubd, score_start=val_s)
        )

    if not fold_scores:
        raise RuntimeError(
            f"No scorable folds: all {skipped_folds} validation windows "
            "predate the earliest universe snapshot. Backfill universe "
            "snapshots (scripts.backfill_universe) and/or extend price "
            "history — see audit 2026-05-15."
        )

    val_sortinos = [s["sortino"] for s in fold_scores if np.isfinite(s["sortino"])]
    val_sortino_mean = float(np.mean(val_sortinos)) if val_sortinos else 0.0

    # Pre-tax mean per-fold return, and a 30%-slab post-tax estimate.
    # Tax is applied only to positive net gains; losses don't get refunded
    # but DO carry forward 8 years in real life — that's not modeled here.
    fold_returns = [
        float(s["equity_curve"].iloc[-1] / INITIAL_CASH - 1)
        for s in fold_scores if len(s["equity_curve"]) > 0
    ]
    pre_tax_return_mean = float(np.mean(fold_returns)) if fold_returns else 0.0
    post_tax_return_mean = float(np.mean([
        r * (1 - STCG_RATE) if r > 0 else r for r in fold_returns
    ])) if fold_returns else 0.0

    side_panel = {
        "calmar_mean": float(np.mean([s["calmar"] for s in fold_scores])) if fold_scores else 0.0,
        "max_dd_worst": float(np.max([s["max_dd"] for s in fold_scores])) if fold_scores else 0.0,
        "hit_rate_mean": float(np.mean([s["hit_rate"] for s in fold_scores])) if fold_scores else 0.0,
        "profit_factor_mean": float(np.mean([
            s["profit_factor"] for s in fold_scores
            if np.isfinite(s["profit_factor"])
        ])) if fold_scores else 0.0,
        "turnover_mean": float(np.mean([s["turnover"] for s in fold_scores])) if fold_scores else 0.0,
        "trade_count_total": int(sum(s["trade_count"] for s in fold_scores)),
        "pre_tax_return_mean": pre_tax_return_mean,
        "post_tax_return_mean_stcg15": post_tax_return_mean,
    }

    all_eq = (
        pd.concat([s["equity_curve"] for s in fold_scores])
        if fold_scores else pd.Series(dtype=float)
    )
    all_trades = (
        pd.concat([s["trades"] for s in fold_scores], ignore_index=True)
        if fold_scores else pd.DataFrame()
    )

    # Chain folds into a continuous equity curve so aggregate drawdown
    # measures real-portfolio risk-of-ruin instead of resetting to $100K
    # every fold. Each fold's per-bar returns are compounded onto the
    # previous fold's ending equity.
    chained_eq_values = [INITIAL_CASH]
    for s in fold_scores:
        fold_eq = s["equity_curve"]
        if len(fold_eq) < 2:
            continue
        fold_returns = fold_eq.pct_change().dropna()
        last = chained_eq_values[-1]
        for r in fold_returns:
            last = last * (1 + r)
            chained_eq_values.append(last)
    chained_eq = pd.Series(chained_eq_values)
    aggregate_max_dd = float(max_drawdown(chained_eq))

    # Per-fold Calmar percentile (informational only — no longer a gate).
    # Folds with no trades are excluded.
    fold_calmars = [
        s["calmar"] for s in fold_scores
        if s["trade_count"] > 0 and np.isfinite(s["calmar"])
    ]
    if fold_calmars:
        lower_quartile_calmar = float(np.percentile(fold_calmars, 25))
    else:
        lower_quartile_calmar = float("nan")

    # Peak position fraction across all folds (informational).
    if len(all_trades) > 0 and "max_position_frac" in all_trades.columns:
        max_position_frac_peak = float(all_trades["max_position_frac"].max())
    else:
        max_position_frac_peak = 0.0

    # Number of folds where the strategy lost money over the window.
    n_negative_folds = int(sum(
        1 for s in fold_scores
        if len(s["equity_curve"]) > 0
        and s["equity_curve"].iloc[-1] < INITIAL_CASH
    ))

    risk_signals = {
        "aggregate_max_dd": aggregate_max_dd,
        "worst_fold_max_dd": side_panel["max_dd_worst"],
        "max_position_frac_peak": max_position_frac_peak,
        "lower_quartile_fold_calmar": lower_quartile_calmar,
        "mean_calmar": side_panel["calmar_mean"],
        "n_negative_folds": n_negative_folds,
        "n_folds": len(fold_scores),
    }

    # Catastrophe-only validator: only fires on >100% gross, >50% aggregate DD,
    # or <20 trades. All other concerns are in risk_signals (informational).
    # Per-fold max gross feeds backtest/risk.py's catastrophe gate. Each fold
    # result carries 'gross_exposure_daily' from backtest/engine.py's
    # GrossExposureRecorder analyzer.
    fold_max_gross = [
        float(s["gross_exposure_daily"].max())
        if len(s["gross_exposure_daily"]) > 0 else 0.0
        for s in fold_scores
    ]
    positions_df = pd.DataFrame({"max_gross_frac": fold_max_gross})
    risk = validate_risk(
        all_trades, all_eq, positions_df,
        trade_count=side_panel["trade_count_total"],
        max_dd=aggregate_max_dd,
    )

    # Per-fold Sortino list — exposes the distribution behind the mean.
    # None for non-finite folds (typically <3 trades). Lets the agent see
    # whether 1.0 is "25 folds at 1.0 each" (robust) or "5 folds at 5.0 +
    # 20 folds at 0.0" (fragile / regime-fragile).
    per_fold_sortinos = [
        round(float(s["sortino"]), 4) if np.isfinite(s["sortino"]) else None
        for s in fold_scores
    ]

    out: dict = {
        "validation_sortino_mean": val_sortino_mean,
        "validation_folds": len(fold_scores),
        "per_fold_sortinos": per_fold_sortinos,
        "side_panel": side_panel,
        "risk": risk,
        "risk_signals": risk_signals,
        # Per-iteration drill-down: full trade list aggregated across folds.
        # The loop driver persists these to iterations/<iter_id>/trades.csv
        # so the dashboard can render winner/loser breakdowns.
        "all_trades": all_trades,
        "all_equity_curve": all_eq,
    }

    if mode == "promotion":
        members, test_ubd = _pit_universe(BACKTEST_END)
        feeds = _load_feeds(
            TEST_BOUNDARY - timedelta(days=WARMUP_CALENDAR_DAYS),
            BACKTEST_END, members,
        )
        test_score = _score_window(
            strategy_cls, feeds, test_ubd, score_start=TEST_BOUNDARY
        )
        out["test_sortino"] = test_score["sortino"]
        out["test_calmar"] = test_score["calmar"]
        out["test_max_dd"] = test_score["max_dd"]
        out["test_hit_rate"] = test_score["hit_rate"]
        out["test_trade_count"] = test_score["trade_count"]

    return out


if __name__ == "__main__":
    import sys
    mode = sys.argv[1] if len(sys.argv) > 1 else "research"
    strat_mod = importlib.import_module("strategy")
    result = evaluate(strat_mod, mode=mode)
    print(f"\n=== mode={mode} ===")
    for k, v in result.items():
        print(f"  {k}: {v}")
