"""IMMUTABLE evaluator for the autoresearch loop.

DO NOT EDIT THIS FILE as part of the inner loop. Editing it constitutes
"changing the rules of the game" and invalidates results across iterations.

Layout:
- Walk-forward over [BACKTEST_START, TEST_BOUNDARY): rolling 2y train,
  6mo validation, slide 3mo. Each validation fold contributes one Sortino;
  the agent optimizes the mean across folds.
- [TEST_BOUNDARY, BACKTEST_END]: SEALED test set. Only revealed in
  mode="promotion".

Run as a script:
    uv run python prepare.py research      # validation only
    uv run python prepare.py promotion     # also reveals test-set scores
"""
from __future__ import annotations

import importlib
import inspect
import os
from datetime import date, datetime, timedelta
from types import ModuleType

import backtrader as bt
import numpy as np
import pandas as pd

from backtest.anti_overfit import compute_rw_mc_null
from backtest.engine import run_backtest
from backtest.metrics import (
    calmar,
    hit_rate,
    max_drawdown,
    profit_factor,
    sortino,
    turnover,
)  # max_drawdown also used directly to compute the chained-fold aggregate DD
from backtest.risk import MIN_TRADES as _CATASTROPHE_MIN_TRADES
from backtest.risk import validate as validate_risk
from data.ingest_prices import read_prices
from data.universe import get_universe_at, snapshot_dates

BACKTEST_START = date(2020, 1, 1)
# India rebuild: NSE bhav archive starts cleanly in late 2019; 2020-01-01 is
# the first month with dense data across the Nifty 500. Train+val spans
# 2020-01 → 2024-12 (~5y, walk-forward folds with 2y train / 6m val / 3m slide);
# sealed test = 2025-01 → 2026-05-14 (~16 months, covers the Jan-26 → Mar-26
# drawdown which is an adversarial regime for momentum strategies — passing
# sealed test here is a meaningful signal). Per spec §6.1.
BACKTEST_END = date(2026, 5, 14)
TEST_BOUNDARY = date(2025, 1, 1)
TRAIN_DAYS = 504
VAL_DAYS = 126
SLIDE_DAYS = 63

# Evaluator fingerprint. Changing the walk-forward rules, the universe-floor,
# or the gate semantics "changes the rules of the game": every KEPT baseline
# recorded under a different version was computed on a DIFFERENT evaluator and
# is NOT a valid comparison anchor (program.md §"evaluator change"). The loop
# stamps this into the journal and only compares against KEPT rows carrying
# the CURRENT version — so a stale poisoned baseline (e.g. the 2.172 spike
# inflated by the pre-2026-05-16 5-name-universe folds) is auto-discarded on
# every branch the moment it picks up this evaluator, with no journal surgery.
# Bump this whenever a change here would alter a prior iteration's score.
EVALUATOR_VERSION = "2026-05-16-univfloor"

# Minimum point-in-time universe size for a walk-forward fold to be SCORED.
# The PIT universe is ~5 names until 2022-07 (broad NSE coverage starts
# 2021-04; the top-200-by-ADV snapshots jump 5→200 on 2022-07-01). A
# cross-sectional strategy on ~5 names is pure noise: no edge (Bonferroni
# p≈1.0), no diversification (60–90% drawdowns), and a thin-vs-full sub-period
# split that makes sub_period_stationarity structurally unpassable. The old
# guard skipped only EMPTY universes, so ~4 quarterly folds ran on 5 names and
# poisoned every backtest. 50 cleanly separates the degenerate 5-name era from
# the real ≥200-name era with margin. (audit 2026-05-16)
MIN_FOLD_UNIVERSE = 50

# Indicator burn-in (audit 2026-05-15 Fix 1). 12-1 momentum needs ~274
# trading days of prior history before it produces ANY signal; a 126-calendar
# (~85-trading-day) val window alone leaves it permanently None → the
# strategy never trades and every metric scores an inert book. We therefore
# load WARMUP_CALENDAR_DAYS of history BEFORE each scored window so the
# strategy enters it already warmed and invested (as it always is live), then
# score ONLY the in-window slice (see _score_window `score_start`). 520
# calendar days ≈ 370 trading days, comfortably > 274 with holiday margin.
# Excluded from scoring, so over-provisioning costs only load time, never
# correctness.
WARMUP_CALENDAR_DAYS = 520
INITIAL_CASH = 50_000.0

# Personal-take-home estimate. Indian resident on Indian (domestic) equities:
# flat 15% STCG (holding < 12 months) and 10% LTCG on gains above a ₹1L
# annual exemption (holding >= 12 months). Reported as a side-panel signal
# only — doesn't enter the agent's optimization (a flat haircut is
# Sortino-invariant). Surcharges (10–37% above ₹50L total income) are NOT
# modeled here; adjust manually if your bracket differs.
STCG_RATE = 0.15
LTCG_HOLDING_DAYS = 365   # 12 calendar months
LTCG_THRESHOLD_INR = 100_000   # ₹1L annual LTCG exemption per FY


# Skip feeds that don't have enough bars for the strategy's longest indicator
# warmup (50-day SMA + small safety margin). With multi-feed strategies,
# loading short-history tickers crashes backtrader's vectorized indicator
# pass with an IndexError. Single-feed didn't expose this because Cerebro
# only built indicators on the first feed.
_MIN_BARS_PER_FEED = 60


def _load_feeds(
    start: date, end: date, tickers: list[str]
) -> dict[str, pd.DataFrame]:
    """Load OHLCV from local DuckDB. Tickers with fewer than _MIN_BARS_PER_FEED
    rows in [start, end] are silently skipped (recent IPOs, mid-window adds,
    delistings).

    Raises only if NO tickers survive, which indicates a setup problem.
    """
    feeds: dict[str, pd.DataFrame] = {}
    for tkr in tickers:
        df = read_prices(tkr, start.isoformat(), end.isoformat())
        if len(df) < _MIN_BARS_PER_FEED:
            continue
        df = df.set_index(pd.DatetimeIndex(df["date"])).drop(columns=["date"])
        feeds[tkr] = df
    if not feeds:
        raise RuntimeError(
            f"No price data with >= {_MIN_BARS_PER_FEED} bars in [{start}, {end}]. "
            "Run data.ingest_prices first."
        )
    return feeds


# Identity sentinel: the load-once-then-slice optimization is numerically
# equivalent ONLY when the loader is span-bounded (the real DuckDB
# implementation). Tests monkeypatch `prepare._load_feeds` with a stub that
# ignores its [start, end] args and returns a fixed canned series for every
# fold; under that stub the old contract is "every fold gets the full series,
# _score_window's score_start does the windowing". Slicing would change that.
# So we only take the global-load fast path when `_load_feeds` is still THIS
# original function; a monkeypatched loader transparently opts out and we use
# the exact legacy per-fold call instead.
_ORIGINAL_LOAD_FEEDS = _load_feeds


def _pit_universe(window_end: date) -> tuple[list[str], dict]:
    """Point-in-time universe for a window ending `window_end`.

    Returns (sorted member union, {snapshot_date: frozenset(tickers)}) using
    ONLY snapshots dated on/before `window_end` — never a future snapshot.
    The strategy resolves the most-recent snapshot ≤ each rebalance date from
    this map. This is audit-2026-05-15 Fix B: it replaces the single frozen
    get_universe_at(BACKTEST_START) that made the whole walk-forward run on
    today's universe. Empty union ⇒ the window predates any snapshot (the
    pre-2021-11 data-starved period); the caller skips such folds.
    """
    sd = [d for d in snapshot_dates() if d <= window_end]
    ubd = {d: frozenset(get_universe_at(d)) for d in sd}
    union = sorted(set().union(*ubd.values())) if ubd else []
    return union, ubd


def _min_active_universe(
    fold_ubd: dict[date, frozenset], val_s: date, val_e: date
) -> int:
    """Smallest PIT snapshot the strategy could be FORCED to trade during
    [val_s, val_e].

    The strategy resolves, at each rebalance bar, the most-recent snapshot
    ≤ that bar. So the snapshots actually in play across the validation
    window are: the one active at val_s (latest ≤ val_s) plus every snapshot
    dated within (val_s, val_e]. A fold is degenerate iff the THINNEST of
    these is below the floor — that is the universe the strategy is squeezed
    into at its worst rebalance in the window. Returns 0 if no snapshot
    predates the window at all (data-starved — skip).
    """
    if not fold_ubd:
        return 0
    keys = sorted(fold_ubd)
    at_or_before_start = [d for d in keys if d <= val_s]
    relevant = [at_or_before_start[-1]] if at_or_before_start else [keys[0]]
    relevant += [d for d in keys if val_s < d <= val_e]
    return min(len(fold_ubd[d]) for d in relevant)


# Strategy params that are plumbing / structure, NOT tunable signal
# hyperparameters — excluded from the parsimony count.
_PLUMBING_PARAMS = frozenset({
    "universe_db_path", "fundamentals_db_path", "macro_db_path",
    "rebalance_weekday", "rebalance_period_weeks", "rebalance_week_parity",
    "enforce_sector_cap", "universe_by_date",
})


def count_hyperparameters(strategy_cls: type) -> int:
    """Count tunable signal hyperparameters on a strategy class (excludes
    plumbing/structure). Used by the parsimony gate. Counted dynamically so
    the loop cannot hide added knobs from the gate."""
    try:
        items = dict(strategy_cls.params._getitems())
    except Exception:  # noqa: BLE001 — backtrader param introspection variance
        return 0
    return sum(
        1 for k, v in items.items()
        if k not in _PLUMBING_PARAMS and isinstance(v, (int, float))
        and not isinstance(v, bool)
    )


_UNIVERSE_FILL_LAG_DAYS = 7


def _universe_respected(all_trades: pd.DataFrame) -> bool:
    """Audit-2026-05-15 #8 guard. True iff EVERY traded ticker was a member
    of the point-in-time universe at its DECISION time. Computed here in the
    IMMUTABLE evaluator from the trade log (not the loop-editable strategy),
    so a variant that ignores the injected universe_by_date and trades
    off-universe names is caught regardless of how its code is written.

    Decision-vs-fill: the strategy selects on the rebalance bar but the order
    fills next-trading-open, so entry_date is the FILL date — up to a long
    weekend + holiday after the decision. If that lag crosses a monthly
    snapshot boundary on which the name legitimately rotated out, checking
    only the entry-date snapshot would false-flag a perfectly legal pick
    (observed: FACT, decided 2023-09-29 when in the Sep universe, filled
    2023-10-03 after it rotated out of the Oct snapshot). So a trade is
    respected if the ticker was a member at entry_date OR in the snapshot
    active ~`_UNIVERSE_FILL_LAG_DAYS` earlier (i.e. at the decision bar).
    Snapshots change only monthly, so this still catches a genuinely
    off-universe pick (absent from BOTH the entry and decision snapshots).
    """
    if all_trades is None or len(all_trades) == 0:
        return True
    if "ticker" not in all_trades.columns or "entry_date" not in all_trades.columns:
        return True
    sd = snapshot_dates()
    if not sd:
        return False  # trades exist but no universe defined at all
    members_by = {d: set(get_universe_at(d)) for d in sd}
    sd_sorted = sorted(sd)
    import bisect

    def _members_window(d: date) -> tuple[set[str] | None, set[str] | None]:
        """(snapshot active at d, snapshot immediately preceding it).

        Tolerance is tied to the snapshot CADENCE, not a fixed day-count.
        The strategy selects from the most-recent snapshot ≤ its DECISION
        bar; the fill (entry_date) is ≥ decision, lagged by the rebalance
        cadence (biweekly ≈ up to 2 weeks) plus real fill delay (NSE
        year-end / festival holiday clusters can push a market fill out
        ~2-3 weeks). That lag can legitimately cross ONE monthly snapshot
        boundary (observed 2026-05-16: SUZLON decided Dec-2023 when in the
        universe, filled 2024-01-15 after it rotated out for the single
        2024-01 snapshot — the old fixed 7-day lookback false-rejected it).
        So a trade is respected if the ticker was a member at the fill
        snapshot OR the one immediately before it. A name absent from BOTH
        was out for ≥1 full snapshot period before any possible decision —
        genuine survivorship / look-ahead, still hard-rejected.
        """
        i = bisect.bisect_right(sd_sorted, d) - 1
        if i < 0:
            return None, None
        cur = members_by[sd_sorted[i]]
        prev = members_by[sd_sorted[i - 1]] if i - 1 >= 0 else None
        return cur, prev

    for row in all_trades.itertuples(index=False):
        tkr = getattr(row, "ticker", None)
        ed = getattr(row, "entry_date", None)
        if tkr is None or ed is None:
            continue
        ed = _as_date(ed)
        t = str(tkr).upper()
        m_fill, m_prev = _members_window(ed)
        if m_fill is None and m_prev is None:
            return False  # traded before any snapshot existed
        if (m_fill is not None and t in m_fill) or (
            m_prev is not None and t in m_prev
        ):
            continue
        return False  # off-universe at fill AND prior snapshot → real violation
    return True


def _sub_period_sortinos(
    fold_val_starts: list[date],
    per_fold_sortinos: list[float | None],
    *,
    months: int = 18,
) -> tuple[float, ...]:
    """Disjoint `months`-long buckets of fold val-starts → mean Sortino per
    bucket. Feeds the sub-period-stationarity gate (regime robustness)."""
    pairs = [
        (vs, s) for vs, s in zip(fold_val_starts, per_fold_sortinos)
        if s is not None
    ]
    if not pairs:
        return ()
    start = min(vs for vs, _ in pairs)
    buckets: dict[int, list[float]] = {}
    for vs, s in pairs:
        idx = ((vs.year - start.year) * 12 + (vs.month - start.month)) // months
        buckets.setdefault(idx, []).append(float(s))
    return tuple(
        float(np.mean(buckets[k])) for k in sorted(buckets)
    )


def _find_strategy_class(module: ModuleType) -> type:
    """Return the single bt.Strategy subclass defined in `module`."""
    candidates = [
        cls for _, cls in inspect.getmembers(module, inspect.isclass)
        if issubclass(cls, bt.Strategy) and cls is not bt.Strategy
    ]
    if not candidates:
        raise RuntimeError(
            f"No bt.Strategy subclass found in {module.__name__}"
        )
    if len(candidates) > 1:
        names = [c.__name__ for c in candidates]
        raise RuntimeError(
            f"Multiple bt.Strategy subclasses in {module.__name__}: {names}. "
            "Define exactly one."
        )
    return candidates[0]


def _slice_feeds(
    global_feeds: dict[str, pd.DataFrame],
    start: date,
    end: date,
    members: list[str],
) -> dict[str, pd.DataFrame]:
    """Per-fold feed slice taken from feeds loaded ONCE for the whole span.

    Behaviourally identical to `_load_feeds(start, end, members)`: a ticker is
    included iff it has >= _MIN_BARS_PER_FEED rows within the inclusive
    [start, end] window. `read_prices` returns a contiguous inclusive
    date-range with no other row filtering, so slicing the wider global frame
    reproduces the exact rows the old per-fold `_load_feeds` returned
    (asserted by tests/test_prepare_parallel.py::test_slice_equals_load).
    """
    s = pd.Timestamp(start)
    e = pd.Timestamp(end)
    feeds: dict[str, pd.DataFrame] = {}
    for tkr in members:
        df = global_feeds.get(tkr)
        if df is None:
            continue
        sl = df.loc[s:e]
        if len(sl) < _MIN_BARS_PER_FEED:
            continue
        feeds[tkr] = sl
    if not feeds:
        raise RuntimeError(
            f"No price data with >= {_MIN_BARS_PER_FEED} bars in "
            f"[{start}, {end}]. Run data.ingest_prices first."
        )
    return feeds


def _run_one_fold(payload: dict) -> tuple[int, dict]:
    """ProcessPool worker: score one walk-forward fold.

    Re-imports the strategy module BY NAME (robust under the 'spawn' start
    method — avoids pickling a dynamically loaded class). Deterministic:
    `_score_window` → `run_backtest` uses no RNG, so the parallel fold scores
    are bit-for-bit identical to the serial loop (asserted by
    tests/test_prepare_parallel.py::test_serial_equals_parallel)."""
    mod = importlib.import_module(payload["mod"])
    cls = _find_strategy_class(mod)
    score = _score_window(
        cls, payload["feeds"], payload["ubd"], score_start=payload["val_s"]
    )
    return payload["idx"], score


def _as_date(x) -> date:
    """Normalize a date / datetime / Timestamp / ISO-string to date."""
    if isinstance(x, date) and not isinstance(x, datetime):
        return x
    if isinstance(x, datetime):
        return x.date()
    ts = pd.Timestamp(x)
    return ts.date()


def _score_window(
    strategy_cls: type,
    feeds: dict[str, pd.DataFrame],
    universe_by_date: dict | None = None,
    score_start: date | None = None,
) -> dict:
    """Run strategy on a single time window; return per-window scoring dict.

    `universe_by_date` ({snapshot_date: frozenset(tickers)}) is forwarded to
    the strategy so it restricts entries to the point-in-time universe at
    each rebalance (audit-2026-05-15 Fix B).

    `score_start` (audit-2026-05-15 Fix 1): when set, the feeds include an
    indicator-burn-in runway BEFORE this date. The strategy trades through
    the warm-up (entering `score_start` already invested, as it always is
    live), but ALL metrics are computed ONLY from `score_start` onward —
    warm-up bars/trades are excluded so they cannot leak into Sortino,
    drawdown, returns, turnover, or the chained equity curve downstream.
    Metric *definitions* are unchanged; only the window they see is the
    intended val/test window. score_start=None ⇒ legacy behaviour (whole
    fed window scored), preserving signal_today / existing tests.
    """
    result = run_backtest(
        strategy_cls, feeds, initial_cash=INITIAL_CASH,
        strategy_kwargs={"universe_by_date": universe_by_date}
        if universe_by_date else None,
    )
    daily = result["daily_returns"]
    trades = result["trades"]
    gross = result["gross_exposure_daily"]
    trade_count = result["trade_count"]

    if score_start is not None:
        # Slice raw daily returns to the scored window, then REBUILD the
        # equity curve from the slice so every downstream consumer
        # (Sortino, max_dd, chained equity, pre_tax_return_mean, risk,
        # gross exposure) sees only in-window P&L. The cut happens here —
        # before _score_window returns — because evaluate() reuses these
        # objects in many places (Codex review 2026-05-15).
        if len(daily) > 0:
            d_mask = [_as_date(i) >= score_start for i in daily.index]
            daily = daily[pd.Series(d_mask, index=daily.index)]
        eq = (1 + daily).cumprod() * INITIAL_CASH if len(daily) > 0 \
            else pd.Series(dtype=float)
        if len(gross) > 0:
            g_mask = [_as_date(i) >= score_start for i in gross.index]
            gross = gross[pd.Series(g_mask, index=gross.index)]
        if len(trades) > 0 and "exit_date" in trades.columns:
            keep = trades["exit_date"].map(
                lambda v: v is not None
                and not pd.isna(v)
                and _as_date(v) >= score_start
            )
            trades = trades[keep].reset_index(drop=True)
        # Closed round-trips realised in-window (TradeRecorder keys by
        # exit_date) — the consistent count for hit_rate/profit_factor.
        trade_count = int(len(trades))
    else:
        eq = result["equity_curve"]

    avg_eq = float(eq.mean()) if len(eq) > 0 else INITIAL_CASH

    return {
        "sortino": sortino(daily),
        "calmar": calmar(daily, eq) if len(eq) > 0 else 0.0,
        "max_dd": max_drawdown(eq),
        "hit_rate": hit_rate(trades),
        "profit_factor": profit_factor(trades),
        "turnover": turnover(trades, avg_eq),
        "trade_count": trade_count,
        "equity_curve": eq,
        "trades": trades,
        "gross_exposure_daily": gross,
    }


def _walk_forward_folds(
    start: date, end: date
) -> list[tuple[date, date, date, date]]:
    """Yield (train_start, train_end, val_start, val_end) tuples."""
    folds: list[tuple[date, date, date, date]] = []
    val_start = start + timedelta(days=TRAIN_DAYS)
    while val_start + timedelta(days=VAL_DAYS) <= end:
        train_start = val_start - timedelta(days=TRAIN_DAYS)
        train_end = val_start - timedelta(days=1)
        val_end = val_start + timedelta(days=VAL_DAYS) - timedelta(days=1)
        folds.append((train_start, train_end, val_start, val_end))
        val_start += timedelta(days=SLIDE_DAYS)
    return folds


def evaluate(strategy_module: ModuleType, mode: str = "research") -> dict:
    """Score a strategy module.

    mode='research'   → returns mean validation Sortino + side panel + risk.
                        Test-set scores are NOT included; the agent never sees them.
    mode='promotion'  → also reveals the locked test-set scores. Run by the
                        human at promotion gate, never by the agent.
    """
    if mode not in ("research", "promotion"):
        raise ValueError(f"mode must be 'research' or 'promotion', got {mode!r}")

    strategy_cls = _find_strategy_class(strategy_module)

    # ── Plan folds: point-in-time universe per fold; skip windows that
    #    predate any universe snapshot (data-starved early period) rather
    #    than fabricate membership.
    plan: list[dict] = []
    skipped_folds = 0
    for (_train_s, _train_e, val_s, val_e) in _walk_forward_folds(
        BACKTEST_START, TEST_BOUNDARY
    ):
        members, fold_ubd = _pit_universe(val_e)
        if (
            not members
            or _min_active_universe(fold_ubd, val_s, val_e) < MIN_FOLD_UNIVERSE
        ):
            skipped_folds += 1
            continue
        plan.append(
            {"val_s": val_s, "val_e": val_e,
             "members": members, "ubd": fold_ubd}
        )

    if not plan:
        raise RuntimeError(
            f"No scorable folds: all {skipped_folds} validation windows "
            f"predate the earliest universe snapshot or fall below the "
            f"MIN_FOLD_UNIVERSE={MIN_FOLD_UNIVERSE} floor (data-starved / "
            "5-name era). Backfill universe snapshots "
            "(scripts.backfill_universe) and/or extend price history — see "
            "audit 2026-05-15 / 2026-05-16."
        )

    # ── Resolve per-fold feeds. Fast path (real span-bounded loader): ONE
    #    DuckDB read of the member union over the whole span, then slice per
    #    fold — consecutive folds' windows overlap ~87% (2y window sliding
    #    3mo), so this replaces ~N_folds × 200-ticker reads. Proven identical
    #    to the old per-fold _load_feeds by tests/test_prepare_parallel.py.
    #    Legacy path (monkeypatched loader, used by the immutable-evaluator
    #    unit tests): exact old per-fold call, contract preserved.
    use_global = _load_feeds is _ORIGINAL_LOAD_FEEDS
    if use_global:
        global_start = min(
            p["val_s"] - timedelta(days=WARMUP_CALENDAR_DAYS) for p in plan
        )
        global_end = max(p["val_e"] for p in plan)
        member_union = sorted({t for p in plan for t in p["members"]})
        global_feeds = _load_feeds(global_start, global_end, member_union)
        for p in plan:
            p["feeds"] = _slice_feeds(
                global_feeds,
                p["val_s"] - timedelta(days=WARMUP_CALENDAR_DAYS),
                p["val_e"],
                p["members"],
            )
    else:
        for p in plan:
            p["feeds"] = _load_feeds(
                p["val_s"] - timedelta(days=WARMUP_CALENDAR_DAYS),
                p["val_e"],
                p["members"],
            )

    # ── Score folds. Folds are fully independent (own feed slice, own
    #    Cerebro, no shared state) and _score_window is deterministic, so
    #    fanning them across processes is numerically identical to the serial
    #    loop — just concurrent. PREPARE_MAX_WORKERS=1 forces the serial path
    #    (the fallback, and what the equivalence test pins). The serial path
    #    is also used when the strategy module can't be re-imported by name
    #    (e.g. __main__ / synthetic test modules under 'spawn').
    mod_name = getattr(strategy_module, "__name__", "")
    importable = (
        mod_name not in ("", "__main__")
        and getattr(strategy_module, "__spec__", None) is not None
    )
    try:
        env_workers = int(os.environ.get("PREPARE_MAX_WORKERS", "0"))
    except ValueError:
        env_workers = 0
    max_workers = (
        env_workers if env_workers > 0
        else min(os.cpu_count() or 1, len(plan))
    )

    if use_global and max_workers > 1 and len(plan) > 1 and importable:
        from concurrent.futures import ProcessPoolExecutor

        payloads = [
            {"idx": i, "mod": mod_name, "feeds": p["feeds"],
             "ubd": p["ubd"], "val_s": p["val_s"]}
            for i, p in enumerate(plan)
        ]
        scored: dict[int, dict] = {}
        with ProcessPoolExecutor(max_workers=max_workers) as ex:
            for idx, score in ex.map(_run_one_fold, payloads):
                scored[idx] = score
        fold_scores = [scored[i] for i in range(len(plan))]
    else:
        fold_scores = [
            _score_window(
                strategy_cls, p["feeds"], p["ubd"], score_start=p["val_s"]
            )
            for p in plan
        ]
    fold_val_starts = [p["val_s"] for p in plan]

    val_sortinos = [s["sortino"] for s in fold_scores if np.isfinite(s["sortino"])]
    val_sortino_mean = float(np.mean(val_sortinos)) if val_sortinos else 0.0

    # Pre-tax mean per-fold return, and a 30%-slab post-tax estimate.
    # Tax is applied only to positive net gains; losses don't get refunded
    # but DO carry forward 8 years in real life — that's not modeled here.
    fold_returns = [
        float(s["equity_curve"].iloc[-1] / INITIAL_CASH - 1)
        for s in fold_scores if len(s["equity_curve"]) > 0
    ]
    pre_tax_return_mean = float(np.mean(fold_returns)) if fold_returns else 0.0
    post_tax_return_mean = float(np.mean([
        r * (1 - STCG_RATE) if r > 0 else r for r in fold_returns
    ])) if fold_returns else 0.0

    side_panel = {
        "calmar_mean": float(np.mean([s["calmar"] for s in fold_scores])) if fold_scores else 0.0,
        "max_dd_worst": float(np.max([s["max_dd"] for s in fold_scores])) if fold_scores else 0.0,
        "hit_rate_mean": float(np.mean([s["hit_rate"] for s in fold_scores])) if fold_scores else 0.0,
        "profit_factor_mean": float(np.mean([
            s["profit_factor"] for s in fold_scores
            if np.isfinite(s["profit_factor"])
        ])) if fold_scores else 0.0,
        "turnover_mean": float(np.mean([s["turnover"] for s in fold_scores])) if fold_scores else 0.0,
        "trade_count_total": int(sum(s["trade_count"] for s in fold_scores)),
        "pre_tax_return_mean": pre_tax_return_mean,
        "post_tax_return_mean_stcg15": post_tax_return_mean,
    }

    all_eq = (
        pd.concat([s["equity_curve"] for s in fold_scores])
        if fold_scores else pd.Series(dtype=float)
    )
    all_trades = (
        pd.concat([s["trades"] for s in fold_scores], ignore_index=True)
        if fold_scores else pd.DataFrame()
    )

    # Chain folds into a continuous equity curve so aggregate drawdown
    # measures real-portfolio risk-of-ruin instead of resetting to $100K
    # every fold. Each fold's per-bar returns are compounded onto the
    # previous fold's ending equity.
    chained_eq_values = [INITIAL_CASH]
    for s in fold_scores:
        fold_eq = s["equity_curve"]
        if len(fold_eq) < 2:
            continue
        fold_returns = fold_eq.pct_change().dropna()
        last = chained_eq_values[-1]
        for r in fold_returns:
            last = last * (1 + r)
            chained_eq_values.append(last)
    chained_eq = pd.Series(chained_eq_values)
    aggregate_max_dd = float(max_drawdown(chained_eq))

    # Per-fold Calmar percentile (informational only — no longer a gate).
    # Folds with no trades are excluded.
    fold_calmars = [
        s["calmar"] for s in fold_scores
        if s["trade_count"] > 0 and np.isfinite(s["calmar"])
    ]
    if fold_calmars:
        lower_quartile_calmar = float(np.percentile(fold_calmars, 25))
    else:
        lower_quartile_calmar = float("nan")

    # Peak position fraction across all folds (informational).
    if len(all_trades) > 0 and "max_position_frac" in all_trades.columns:
        max_position_frac_peak = float(all_trades["max_position_frac"].max())
    else:
        max_position_frac_peak = 0.0

    # Number of folds where the strategy lost money over the window.
    n_negative_folds = int(sum(
        1 for s in fold_scores
        if len(s["equity_curve"]) > 0
        and s["equity_curve"].iloc[-1] < INITIAL_CASH
    ))

    risk_signals = {
        "aggregate_max_dd": aggregate_max_dd,
        "worst_fold_max_dd": side_panel["max_dd_worst"],
        "max_position_frac_peak": max_position_frac_peak,
        "lower_quartile_fold_calmar": lower_quartile_calmar,
        "mean_calmar": side_panel["calmar_mean"],
        "n_negative_folds": n_negative_folds,
        "n_folds": len(fold_scores),
    }

    # Catastrophe-only validator: only fires on >100% gross, >50% aggregate DD,
    # or <20 trades. All other concerns are in risk_signals (informational).
    # Per-fold max gross feeds backtest/risk.py's catastrophe gate. Each fold
    # result carries 'gross_exposure_daily' from backtest/engine.py's
    # GrossExposureRecorder analyzer.
    fold_max_gross = [
        float(s["gross_exposure_daily"].max())
        if len(s["gross_exposure_daily"]) > 0 else 0.0
        for s in fold_scores
    ]
    positions_df = pd.DataFrame({"max_gross_frac": fold_max_gross})
    risk = validate_risk(
        all_trades, all_eq, positions_df,
        trade_count=side_panel["trade_count_total"],
        max_dd=aggregate_max_dd,
    )

    # Per-fold Sortino list — exposes the distribution behind the mean.
    # None for non-finite folds (typically <3 trades). Lets the agent see
    # whether 1.0 is "25 folds at 1.0 each" (robust) or "5 folds at 5.0 +
    # 20 folds at 0.0" (fragile / regime-fragile).
    per_fold_sortinos = [
        round(float(s["sortino"]), 4) if np.isfinite(s["sortino"]) else None
        for s in fold_scores
    ]

    # ── Anti-overfit gate inputs (computed in the IMMUTABLE evaluator so the
    #    loop cannot fabricate them). Consumed by backtest.anti_overfit via
    #    scripts.loop. The aggregate net daily-return series is the chained
    #    walk-forward equity's bar returns (scored windows only, after costs).
    #
    # Compute short-circuit (audit 2026-05-16): the 5000-permutation MC is the
    # single dominant cost per iteration. A variant that already fails a CHEAP,
    # deterministic disqualifier — non-positive Sortino (won't compound),
    # < min-trades (catastrophe-sparse), or off-universe (hard reject) — is
    # going to be REVERTED no matter what the MC says. Skipping the MC for
    # those and assigning the worst-case null (p=1.0, pct=0.0) is consistent
    # (bonferroni/rw_mc would fail anyway) and stops the loop burning compute
    # on doomed variants. Genuine candidates still get the full MC.
    universe_ok = _universe_respected(all_trades)
    n_trades_total = int(side_panel["trade_count_total"])
    cheap_disqualified = (
        val_sortino_mean <= 0.0
        or n_trades_total < _CATASTROPHE_MIN_TRADES
        or not universe_ok
    )
    chained_daily = chained_eq.pct_change().dropna().to_numpy()
    if chained_daily.size >= 2 and not cheap_disqualified:
        def _sortino_arr(a: np.ndarray) -> float:
            return float(sortino(pd.Series(a)))
        orig_sortino = _sortino_arr(chained_daily)
        rw_pct, rw = compute_rw_mc_null(
            chained_daily, _sortino_arr, n_permutations=5000
        )
        # Permutation p-value (temporal-exchangeability null), +1 smoothing.
        sortino_val_pvalue = float(
            (np.sum(rw >= orig_sortino) + 1) / (len(rw) + 1)
        )
        rw_mc_null_pct = float(rw_pct)
    else:
        sortino_val_pvalue = 1.0
        rw_mc_null_pct = 0.0

    anti_overfit = {
        "sortino_val_mean": val_sortino_mean,
        "sortino_val_pvalue": sortino_val_pvalue,
        "rw_mc_null_pct": rw_mc_null_pct,
        "sub_period_sortinos": list(
            _sub_period_sortinos(fold_val_starts, per_fold_sortinos)
        ),
        "n_hyperparameters": count_hyperparameters(strategy_cls),
        "n_trades": n_trades_total,
        "aggregate_dd": aggregate_max_dd,
        "universe_respected": universe_ok,
    }

    out: dict = {
        "anti_overfit": anti_overfit,
        "evaluator_version": EVALUATOR_VERSION,
        "validation_sortino_mean": val_sortino_mean,
        "validation_folds": len(fold_scores),
        "per_fold_sortinos": per_fold_sortinos,
        "side_panel": side_panel,
        "risk": risk,
        "risk_signals": risk_signals,
        # Per-iteration drill-down: full trade list aggregated across folds.
        # The loop driver persists these to iterations/<iter_id>/trades.csv
        # so the dashboard can render winner/loser breakdowns.
        "all_trades": all_trades,
        "all_equity_curve": all_eq,
    }

    if mode == "promotion":
        members, test_ubd = _pit_universe(BACKTEST_END)
        feeds = _load_feeds(
            TEST_BOUNDARY - timedelta(days=WARMUP_CALENDAR_DAYS),
            BACKTEST_END, members,
        )
        test_score = _score_window(
            strategy_cls, feeds, test_ubd, score_start=TEST_BOUNDARY
        )
        out["test_sortino"] = test_score["sortino"]
        out["test_calmar"] = test_score["calmar"]
        out["test_max_dd"] = test_score["max_dd"]
        out["test_hit_rate"] = test_score["hit_rate"]
        out["test_trade_count"] = test_score["trade_count"]

    return out


if __name__ == "__main__":
    import sys
    mode = sys.argv[1] if len(sys.argv) > 1 else "research"
    strat_mod = importlib.import_module("strategy")
    result = evaluate(strat_mod, mode=mode)
    print(f"\n=== mode={mode} ===")
    for k, v in result.items():
        print(f"  {k}: {v}")
